# Header
menu:
  首页: /
  归档: /archives
  游戏高分榜: /nodejs/wechat/ranking-list
  数据库: /phpmyadmin

rss: /atom.xml
nav: left
mobile_nav: left



# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- userinfo
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Background
# background_image: /images/avatar1.jpeg
background_title: 图片来自网络

#Userinfo
author: 如歌如羽
slogan: 移动前端开发工程师、Android开发工程师、IOS开发工程师、全栈开发工程师
avatar: /images/avatar1.jpeg
avatar_title: 图片来自网络

# Article code panel: cloud doorframe mac
highlightPanel: cloud

#Gitment
gitment:
  enable: true
  owner: Tim-Shadow
  repo: hero.wanyan.site
  client_id: 46ba7fc30923a2823db1
  client_secret: 85f0d6bf4f24d13a76afd1de0100b85654526f85

# Miscellaneous
google_analytics:
gauges_analytics:
google_site_verification: 
baidu_site_verification: 
favicon: /images/default-avatar.webp
twitter:
fb_admins:
fb_app_id:
keywords:

